name: verif_id
description: A clean and elegant Flutter package for KYC verification (selfie, 15s video, ID front/back, review + submit). French TTS instructions by default.
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter_tts: ^4.2.3
  path_provider: ^2.1.5
  image: ^4.5.4
  video_player: ^2.10.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
